### ISSUE TITLE
Ash: 7 - Customizing Actions - Close Ticket throws Framework Error

### ISSUE THREAD

**Issue by danielschnee** [ash-project/ash_tutorial#25] opened 2024-05-01 16:20 UTC
Still after deleting the livebook session, starting the session again and copy pasting every solution i get an `Framework Error` on the `Close Ticket` section.

Right now i'm not able to fix this without introducing atomic update.

![image](https://github.com/ash-project/ash_tutorial/assets/62013481/cc3914c1-d4ff-4099-bb68-66856a608835)

**Comment by zachdaniel** [comment] 2024-05-01 20:29
Interesting! That doesn't happen for me 🤔

**Comment by zachdaniel** [comment] 2024-05-01 20:31
![CleanShot 2024-05-01 at 16 31 01](https://github.com/ash-project/ash_tutorial/assets/5722339/c88924a7-5486-45c0-a5be-2fc82ee2af61)

Perhaps something we fixed in a version since you set up the Livebook? If you add `force: true` to the `Mix.install` call and rerun the setup, it will download the latest version.

**Comment by zachdaniel** [comment] 2024-05-01 20:31
Will close for now, but happy to reopen if we can reproduce the issue.

**Closed as completed by zachdaniel** 2024-05-01 20:31 UTC

**Comment by danielschnee** [comment] 2024-05-03 07:57
Maybe something with my livebook hosting is not working correctly.

I tried `force: true` and `ash@rc_41` got installed. But i got the same error:

![image](https://github.com/ash-project/ash_tutorial/assets/62013481/2d499ec2-58ae-4cfc-ac78-14d8a2136932)

Interesting is that the help link links to `rc_15` but in the stack trace you can see it is using `rc_41`.

**Comment by zachdaniel** [comment] 2024-05-03 14:36
Hm...that is really strange. At this point it's probably a question about `Mix.install`. I think you could edit the setup block to point to the latest release candidate in the meantime?

**Comment by danielschnee** [comment] 2024-05-04 08:41
Found a solution. Adding `defaults [:read]` to the `actions` solved it in the end for me.

@zachdaniel does it make sense to add that to the `Solution` example?

**Comment by zachdaniel** [comment] 2024-05-04 09:49
Yep! PRs welcome 🙏
